# This file contains values from Cookiecutter

default_context:
  project_name: "gpucompare"
  project_description: "Compare GPUs"
  organization: "kHarshit"
  license: "MIT"
  minimal_python_version: 3.9
  github_name: "kHarshit"
  email: "kumar_harshit@outlook.com"
  version: "1.0.0"
  line_length: "88"
  create_example_template: "cli"
